### ISSUE TITLE
Is Fractureiser still a threat?

### ISSUE THREAD

**Issue by Millipede406** [fractureiser-investigation/fractureiser#105]
Not sure if this is the place for questions, but the minecraft reddit is currently privated and I simply just want to know if fractureiser is still something I should be concerned about.

I want to start a minecraft server for the 1.20 update with a few friends, and we usually use some performance mods (like sodium). How risky would it be to download these mods? I have searched the internet but I haven't really found a conclusive answer so I was hoping someone here would be able to clear it up. Thank you!

(Also I am very sorry if this is not the place for questions. If it is not, I would appreciate it if you could direct me to the right place)

**Comment by ItzSwirlz** [comment]
New infections are currently not possible, existing ones may be active. CurseForge scanned and removed all infected jar files, but yesterday they did find more infected bukkit plugins, so just be careful. Read the docs/users.md file for details.

**Comment by Millipede406** [comment]
> New infections are currently not possible, existing ones may be active. CurseForge scanned and removed all infected jar files, but yesterday they did find more infected bukkit plugins, so just be careful. Read the docs/users.md file for details.

Are there any active infected jar files on modrinth? Or should I be good?
