### ISSUE TITLE
Is a file folder that is just Microsoft safe?

### ISSUE THREAD

**Issue by Shell2248** [fractureiser-investigation/fractureiser#111]
I followed the steps to find out if I'm infected and I only have one folder that is just named Microsoft. There are no other folders having anything to do with Microsoft, is this an issue?

**Comment by Nitrrine** [comment]
No, this is legitimate and official folder

**Comment by Shell2248** [comment]
Thank you, I am not necessarily the best when it comes to files, I am just a kid that likes mods.
