### ISSUE TITLE
Weird folders created in AppData\Roaming... Related to fractureiser?

### ISSUE THREAD

**Issue by DexrnZacAttack** [fractureiser-investigation/fractureiser#112]
They seem to be mimicing some kind of filestructure (from where I do not know).

Each folder has a file in it, and can have varying names, in my case, there were these files:
1. unity.psp (inside blue-helmets, 3kb in size, modified on 6/9/2023 at 9:45 PM (I MAY HAVE EDITED IT, I DO NOT REMEMBER), created at 5/31/2023 at 11:03 PM)
2. work.json (inside ts-modmail, 1kb in size, modified on 5/31/2023 at 11:03 PM, created at 5/31/2023 at 11:03 PM)
3. rec.lm (inside jun-takahashi, 3kb in size, modified on 5/31/2023 at 11:03 PM, created at 5/31/2023 at 11:03 PM)

rec.lm and unity.psp are ALMOST the same as eachother, with a bunch of numbers inside, and the first 293 characters being the EXACT SAME, I do not know what they mean and don't want to show it in case of it being something else, like some kind of identifier or something. I will show a snippet of each though.
work.json however has a different set of numbers. 

rec.lm and unity.psp:
_
6E71FC6E25A4B3 (there are 2738 more numbers)

work.json:
_
60BF812A87CABB (there are 388 more numbers)

I feel like I have deleted them before, but they have reappeared...

![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/1142baf9-4267-489c-91b4-5e7ab0a73d77)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/78ec9204-c76a-412a-b5a9-d5e1d5724d46)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/0806fee4-f0b1-4640-860f-0b6db880472c)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/281b9a87-d654-436f-8ed9-4bac9e96422c)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/21db54a2-2b63-463a-aa84-6dba967b5926)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/1afbad19-8d3c-4815-8ead-b65291f36f01)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/e62e9c17-4619-4486-b9d8-57223972ad8c)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/ee51fe82-d06d-4f6d-9c58-c7213ef265a6)
![image](https://github.com/fractureiser-investigation/fractureiser/assets/60078656/99bd4cae-37bd-4963-b7a4-5651020b0d53)

**Comment by DexrnZacAttack** [comment]
> does Midnight scp:sl / midnight.im mean something to you? These are apparantly tracing files of that cheat. https://t.me/MidnightSCP/189
> 
> Edit: why do i even help filthy cheaters

I played SCP:SL once and havent installed cheats...

**Comment by DexrnZacAttack** [comment]
I got in contact with the friend and they have the same folders, but they are saying that the ts-modmail is from a plugin for reporting users that is installed on a server

**Comment by InvitedRhino683** [comment]
hi im that friend

im a mod on an scp sl server so i know a tiny bit more than he does, but i have never once installed a cheating client for scp sl in my life ever and i have these exact same folders as well with the exact same files (size is different though), so honestly i dont even know how i got these either. probably from some plugin or something

**Comment by unascribed** [comment]
So, not Fractureiser. Completely different game.

**Comment by DexrnZacAttack** [comment]
Seems like it, sorry about that!
