### ISSUE TITLE
point of interest

### ISSUE THREAD

**Issue by TheQuantumAnchovie** [fractureiser-investigation/fractureiser#113]
I was intrigued by the article mentioning that the fractureiser bukkit was marked as being last active on jan 1st 2000, so i went to take a look, and the user page now states:
`Member for 22 days and 10 hours
Last active Fri, Dec, 31 1999 19:00:00`
what does this mean? who knows! probably nothing, maybe a surreptitious method of communication, maybe a weird glitch?
in any case, i hope u found this interesting!

**Comment by Janmm14** [comment]
Nobody knows, its jsut a minor detail anyway.

**Comment by unascribed** [comment]
Whether it says Jan 1 2000 or Dec 31 1999 depends on your time zone. I believe it's an artifact of the account never having been logged in to, only used via the API.
