### ISSUE TITLE
Add prevention techniques to README

### ISSUE THREAD

**Issue by Elara6331** [fractureiser-investigation/fractureiser#14]
Linux users can theoretically prevent stage 1 from saving stage 2 using filesystem permissions by pre-making the `~/.config/.data` directory, making it owned by root, and setting the immutable flag. This can be accomplished with the following commands:

```bash
mkdir ~/.config/.data
sudo chown root:root ~/.config/.data
sudo chattr +i ~/.config/.data
```

(Edit: found a better way to prevent the directory from being deleted)

**Comment by LogoiLab** [comment]
There should be an entire `mitigations.md`

That can house links to all the scanners, yara rules, etc as well as a brief summary of how to use them.

**Comment by Flipt-al** [comment]
Am going to start work on the mitigations

**Comment by orowith2os** [comment]
Linux users can also prevent this malware from being able to do anything (like create files) in the first place by using Flatpak, the default Prism Launcher Flatpak settings are a good reference for this. The malware just writes to a tmpfs that gets wiped on an app restart.

**Comment by unascribed** [comment]
Consolidating this with #52. I'm unsure of the value of listing these — they're fragile and specific to only the variants we've documented, but if y'all want to discuss this and prepare a document thats's now the right place.
