### ISSUE TITLE
Important Question

### ISSUE THREAD

**Issue by Name36154** [fractureiser-investigation/fractureiser#15]
I found a shortcut in the mentioned file path on my windows system, it had the same name as an installed app, is this definitely the file and what course of action should I take?

**Comment by electricsteve** [comment]
delete the file, if it wasn't a infected file the program will probably download it again. but to be sure delete it imediately!

**Comment by Name36154** [comment]
Do you know how quickly it will download again? as it hasn't downloaded again and I first found it about 10-15 minutes ago

**Comment by Name36154** [comment]
> restart in safe mode, run overwolf's scanner tool and nekoscanner, you may need to nuke all your jars and reinstall

I know I am dumb, but how do you restart in safe mode, and how do you run the scanners?

**Comment by ItzSwirlz** [comment]
> From review, it looks like the malicious shortcut is called `.lnk`

all windows shortcuts are, but if the original file can be traced, i think (not sure) windows can tell you (maybe?) how many files link back to it

**Comment by williewillus** [comment]
> all windows shortcuts are

all windows shortcuts *end in* `.lnk`, but the malicious is called `.lnk` outright.

**Comment by Name36154** [comment]
oh thank you so much, I was getting nervous and I was gonna end up staying up late to reset everything! you have saved me from many bad days
