### ISSUE TITLE
Could the fractureiser potentially have more stages, or maybe other ways of spreading other than just .jars?

### ISSUE THREAD

**Issue by ger3tto** [fractureiser-investigation/fractureiser#19]
title. i am really curious and it is 2am

**Comment by xyzeva** [comment]
The current C2 servers are all nullrouted, we are currently reversing `Stage3b` which is another malware family that was used to target blackspigot. This has its own C2 that has not been nullrouted, so yes. But its jumping to another family.

**Comment by ger3tto** [comment]
Interesting. Any testing with VirusTotal?

**Comment by unascribed** [comment]
Yes, this is a network-based malware, it may change at any time. This is why the document is worded how it is.
