### ISSUE TITLE
I'm on Mac, what do i do to check that i'm not infected?

### ISSUE THREAD

**Issue by ShroomiePerson** [fractureiser-investigation/fractureiser#21]

**Comment by xyzeva** [comment]
The malware does not work on mac.

**Comment by ShroomiePerson** [comment]
thank you! i'll try my best to be safe

**Comment by ShroomiePerson** [comment]
> its recommended to run nekoscanner or overflows detection tool mentioned in docs/user.md

wait, neither 'nekoscanner' or 'overflows detection tool' are mentioned in /docs/users.md
