### ISSUE TITLE
where can i find a copy of an infected jar file?

### ISSUE THREAD

**Issue by matthewg-rev** [fractureiser-investigation/fractureiser#23]
Just out of plain curiosity I'd like to know where to find one of these infected mods so I can study it myself.

**Comment by xyzeva** [comment]
The following are all completely malware, do not run any of them but:

Listing:
- https://minio.buyvm-lux-1.semisol.dev/fractureiser-malware-samples/NekoClient-stage3-deobf-src.zip, deobfuscated source code of stage 3
- https://minio.buyvm-lux-1.semisol.dev/fractureiser-malware-samples/deobf_client.zip
- https://minio.buyvm-lux-1.semisol.dev/fractureiser-malware-samples/obf_client.zip
- https://minio.buyvm-lux-1.semisol.dev/fractureiser-malware-samples/sample2.zip
- https://minio.buyvm-lux-1.semisol.dev/fractureiser-malware-samples/stage2.zip
- https://minio.buyvm-lux-1.semisol.dev/fractureiser-malware-samples/cfmalware-files-honbra.zip

**Comment by jaskarth** [comment]
Closing for less visibility.
