### ISSUE TITLE
Incorrect assumption

### ISSUE THREAD

**Issue by LogoiLab** [fractureiser-investigation/fractureiser#31]
https://github.com/fractureiser-investigation/fractureiser/blob/b8173b003de6b1d750ba1b36bfc6fc1e1a0b19fc/docs/users.md?plain=1#L50

We cannot assume that this will only affect MC related jars. Do not perpetuate dangerous assumptions.

**Comment by Teapot4195** [comment]
That is correct, it can propagate to other jars as well, if I'm not wrong
