### ISSUE TITLE
Use a consistent Markdown formatter

### ISSUE THREAD

**Issue by HonbraDev** [fractureiser-investigation/fractureiser#32]
We currently don't have an agreed-upon formatter for Markdown files. This can potentially result in merge commits.

**Comment by AtomicGamer9523** [comment]
agree

**Comment by AtomicGamer9523** [comment]
We could make everyone have their changes go through https://codebeautify.org/markdown-formatter (default settings)

**Comment by williewillus** [comment]
This doc is low traffic enough that I don't think this should be a priority we spend our time on. Just send the PR's and I'll review them
