### ISSUE TITLE
Access Virus Files

### ISSUE THREAD

**Issue by lucasrpatten** [fractureiser-investigation/fractureiser#45]
I would like to access some of the mod files (for decompilation), but all the mods have been taken down from their host sites. Does anyone have access to any of these?

**Comment by williewillus** [comment]
Please join irc for active discussion and sample links

**Comment by xylemlandmark** [comment]
Stage0 is pretty thoroughly investigated by this point, as it's incredibly small and simple. Right now we're on the lookout for *new strains* of Stage0.
