### ISSUE TITLE
I'm Not Infected, Now What? I'm **NOT** Infected, Now What?

### ISSUE THREAD

**Issue by Rocxks** [fractureiser-investigation/fractureiser#50]
stop spreading missinformation "I'm Not Infected, Now What?"

The absolute safest thing you can do at the moment is to not launch Minecraft at all. Yes, even Vanilla.
We do not know 100% everything that's compromised, and there's no way to guaranteed any one given installation has not been corrupted by a step of the code we have not found yet." you kept ignoring my pull requests and ignoring the **NOT** In every of my fix this, YOU ARE SAFE WHEN YOU ARE USING VANILLA ive already pulled 2 requests on this and ignore me you are totally trying to spread missinformation

**Comment by williewillus** [comment]
I don't know how many times I have to tell you, we have found code in Stage 3 that directly attempts to inject itself into vanilla https://github.com/clrxbl/NekoClient/blob/fd76c5f9d40d1e10de11f00a6b4e0cca3d6221a3/dev/neko/nekoinjector/template/impl/MinecraftClientTemplate.java#L11

stop spamming this repository or you're getting blocked.

**Comment by DataDalton** [comment]
I think what they're trying to say, in not a good way, is that if you only play vanilla that this malware does not impact you

**Comment by Rocxks** [comment]
nah hes only trying to spread missinformation theres no way hes not trolling hes just a newgen who hasnt learned what NOT is

**Comment by DataDalton** [comment]
> nah hes only trying to spread missinformation theres no way hes not trolling hes just a newgen who hasnt learned what NOT is

I was speaking about you

**Comment by Rocxks** [comment]
I wasnt talking abt that reply you made

**Comment by Rocxks** [comment]
i litteraly made 2 pull requests and they forget to read "NOT"

**Comment by Rocxks** [comment]
![image](https://github.com/fractureiser-investigation/fractureiser/assets/134576673/31882fbf-c004-424d-a682-36edc883fdef)
now what do i have to play minecraft when i AM infected but not when im not infected, that will be more understandable

**Comment by unascribed** [comment]
The part you're missing is the context of this section — the current methods we know of to check for an infection of the virus is *only* for the strains *we know of*. Due to the nature of this virus, we *cannot be sure* — it can infect any JAR file, including vanilla Minecraft versions that have already been downloaded.

**Comment by Rocxks** [comment]
you are MISSING THE PART WHERE I SAID ITS THE SECTION WHERE IT SAYS *************************NOT**************************** *******INFECTED******* you are just trying to keep your missinformation up
