### ISSUE TITLE
making a logo for malicious virus is cringe and insensitive 

### ISSUE THREAD

**Issue by TypicalGhostGuy22** [fractureiser-investigation/fractureiser#58]

**Comment by unascribed** [comment]
Logos help publicize research efforts and raise awareness. It may be "cringe" but it's necessary in today's landscape.

**Comment by williewillus** [comment]
https://heartbleed.com/
https://meltdownattack.com/
https://en.wikipedia.org/wiki/Foreshadow

don't hate the players hate the game
