### ISSUE TITLE
Including ref ID in "Known affected mods & plugins"?

### ISSUE THREAD

**Issue by SilverAndro** [fractureiser-investigation/fractureiser#62]
Given fractureiser uses this ref ID itself to keep track of infection point I think it would make sense to put the included IDs in the table as well

**Comment by unascribed** [comment]
Someone will need to acquire all the ref IDs; I'm unsure how helpful these values are, they appear to be random numbers. As such, I'm not convinced this is worth the time and effort of the team to track down, given just how many variants we've found.

Regardless, a full Stage3 infection will re-randomize the ref IDs on new files, so it can't even really track spread — it appears to be a way for the attacker to track initial infection sources, and as such is not terribly useful for us.
