### ISSUE TITLE
Misinformation in 2023-06-08-meeting regarding Flatpak

### ISSUE THREAD

**Issue by orowith2os** [fractureiser-investigation/fractureiser#67]
The file says the following:

> Second, is using a system such as Flatpak, but notably in its default configuration Flatpak and other containerization systems [are not sandboxes](https://hanako.codeberg.page/).

This is not true, and the author at the linked website is twisting the meaning of the word "sandbox" to fit their definition of the word. The Flatpak sandbox *is* a sandbox, regardless of what permissions you give it. The Flatpak sandbox is also strictly sandboxed in its default configuration, some application maintainers just decide to loosen it as required such that the applications work properly. 

Also noting that, in the Prism Launcher Flatpak, the malware is utterly unable to function, even with a potential sandbox escape in `device=all`. This was not an opt-in sandbox, but opt-out.

Eventually, the hope is for Portals and Flatpak to become expected for application distribution, and for your off-the-shelf application to not require any potential sandbox escapes in order to function properly. But some applications partially disabling the sandbox does not quality it to not be considered a sandbox.

**Comment by williewillus** [comment]
Thanks, I'll remove it. Though overall the conversation should be focused on windows since that's where all the users are
