### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by Panedwards** [fractureiser-investigation/fractureiser#69]
Rather than "Modded Players" maybe put "Mod Users"

**Comment by unascribed** [comment]
It used to say "Mod Players", no one can agree on what the right one is. The meaning is clear, nitpicking is not constructive while we try to get this under control and documented.

**Comment by Panedwards** [comment]
I wasn't" Nitpicking" I was just suggesting, however you do what you want.

**Comment by unascribed** [comment]
You opened an issue and sent a notification to the entire team over an ambiguous piece of grammar that's [already been debated](https://github.com/fractureiser-investigation/fractureiser/pull/46).
