### ISSUE TITLE
We've locked issues and PRs

### ISSUE THREAD

**Issue by unascribed** [fractureiser-investigation/fractureiser#72]
We're a small team trying our best to get this all documented and researched so the community can know what's up and what to do.

Constantly fielding good-faith but ultimately unconstructive PRs eats into our limited time and so we have opted to lock the repo.

Please join us on IRC if you would like to discuss things.

**Comment by unascribed** [comment]
We've unlocked as things have calmed down.

**Comment by HopperElec** [comment]
Should this issue not be unpinned too? Or maybe renamed?

**Comment by unascribed** [comment]
Whoops, meant to unpin it and forgot. Today has been a bit of a whirlwind for me.
