### ISSUE TITLE
Are OpenRC systems affected?

### ISSUE THREAD

**Issue by lima-limon-inc** [fractureiser-investigation/fractureiser#91]
Thank you @Vazkii for warning the community about the virus.

Is there any evidence that suggests that systems running open rc were affected by these viruses?

PS: I'm a big fan of your work

**Comment by Rix565** [comment]
Yes, as the virus infect .jar files without any Linux/Windows vulnerability.

**Comment by unascribed** [comment]
Fractureiser is only capable of persistence on Linux via an *attempt* to drop systemd units, but it will only work if the malware is run as root — the user unit is not correctly formed and never works.

However, it can still run to completion on any Linux system, regardless of its init daemon. A Stage3 infection would proceed to infect all writeable Stage0 on the filesystem that look like Minecraft mods/plugins or executable jar files, and would re-run every time an infected Stage0 jar is run. As such, OpenRC, Upstart, et al are just as affected as systemd.

**Comment by lima-limon-inc** [comment]
Thanks for the clarification!
