### ISSUE TITLE
old downloaded mods are infected?

### ISSUE THREAD

**Issue by gferradas** [fractureiser-investigation/fractureiser#92]
Hi, not sure how to say this but is it possible that mods that i downloaded before the vulnerability are infected?

im not sure how the mods work if they download some things when you install them or something similar 

also if there is some how to contribute with the project?

thank you for your effort 👍

**Comment by FelixCharm** [comment]
it's possible, your best bet is to check if you're infected using the methods talked about [here](https://github.com/fractureiser-investigation/fractureiser/blob/main/docs/users.md#am-i-infected)

**Comment by gferradas** [comment]
f*** me i didnt notice any cpu ram spike when the post happend but i check just in case

**Comment by Janmm14** [comment]
We never claimed the malware would spike cpu or ram
