### ISSUE TITLE
Are there any ways to automatically scan for stage 2?

### ISSUE THREAD

**Issue by thecinnabonmanager** [fractureiser-investigation/fractureiser#93]
I've manually checked for the `Microsoft Edge` folder and found nothing, but I am still quite paranoid. Is there any program to automatically scan it like the Overwolf .jar scanner? Or is the only way to check to do it manually? Thank you.

**Comment by unascribed** [comment]
Most antimalware engines (Kaspersky, BitDefender, F-Secure, AVG, McAfee, [and many more](https://www.virustotal.com/gui/file/f1a6565d3fb13dd412020cd11cae082ea4eb67cea0d5b55f3ee5de43f52e28dd)) now detect most forms of Fractureiser, other than Stage0 as each sample is unique — this is why the modding community has developed custom scanners for Stage0. If in doubt, run a full system scan with your antivirus tool.

**Comment by soot716** [comment]
what about malwarebytes?

**Comment by Janmm14** [comment]
@soot716 
Last time I tried getting malwarebytes to detect jars, they said that Malwarebytes only handles jar files via runtime detection. So only Premium protects you.

Stage2 should be detected by microsoft defender given you enable Cloud feature.

**Comment by soot716** [comment]
thank you so much!
