### ISSUE TITLE
Windows defender marks overwolf's scanner as dangerous

### ISSUE THREAD

**Issue by Krzysiek127** [fractureiser-investigation/fractureiser#96]
I've downloaded ow's scanner and used it (thank god no fractureiser detected, no "Microsoft Edge" folder either)
but then windows defender notified me that this scanner is dangerous (Sabsik.FL.B!ml) and deleted it.
I've downloaded it from this thread so i shouldn't worry, right?

**Comment by RealmKebab** [comment]
it's just a false positive, you can add the scanner to the exceptions section @Krzysiek127

**Comment by iam-py-test** [comment]
Report a false positive to M$: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by Krzysiek127** [comment]
Ok thanks
