### ISSUE TITLE
Uninstall Java on system

### ISSUE THREAD

**Issue by Danjhop4** [fractureiser-investigation/fractureiser#97]
If you use just minecraft uninstall java so when you clear the mods the virus can’t run on your system

**Comment by Janmm14** [comment]
the current virus servers are down, but it had a script which downloaded and installed java, so useless advice

**Comment by RealmKebab** [comment]
^

**Comment by Danjhop4** [comment]
> the current virus servers are down, but it had a script which downloaded and installed java, so useless advice

it failed to install properly any ways
